spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  datasource:
    username: scushiposhi
    password: authentication
    url: jdbc:postgresql://localhost:5432/db_authentication
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: debug
      hibernate: debug
